config/routes.rb
Rails.application.routes.draw do
  passwordless_for :users, at: '/'

  get 'notifications/index'

  get "t/sitemap", to: "sitemap#index", as: :sitemap, defaults: { format: "xml" }

  get 'sign_up', to: 'users#new', as: :sign_up
  post 'users/confirm', to: 'users#confirm', as: :confirm
  get 'users/register/:token', to: 'users#register', as: :register
  post 'users', to: 'users#create', as: :create_user
  delete 'users/:id', to: 'users#destroy', as: :delete_user

  get '/notifications', to: 'notifications#index', as: :notifications

  root 'posts#index'
  get "/latest", to: "posts#latest", as: :latest
  get "/pinned", to: "posts#pinned", as: :pinned
  get "posts/:id", to: "posts#show", as: :post
  post "posts", to: "posts#create", as: :create_post
  patch "posts/:id", to: "posts#update", as: :update_post
  delete "posts/:id", to: "posts#destroy", as: :delete_post
  get '/posts/:id/pin_button', to: 'posts#pin_button', as: :post_pin_button

  post '/posts/:post_id/pins', to: 'pins#create', as: :create_pin
  delete '/posts/:post_id/pins/:id', to: 'pins#destroy', as: :delete_pin

  get '/posts/:post_id/reactions', to: 'post_reactions#index', as: :post_reactions
  post '/posts/:post_id/reactions', to: 'post_reactions#create', as: :create_post_reaction
  delete '/posts/:post_id/reactions/:id', to: 'post_reactions#destroy', as: :delete_post_reaction

  get '/posts/:post_id/comments', to: 'comments#index', as: :comments
  post '/posts/:post_id/comments', to: 'comments#create', as: :create_comment
  delete '/posts/:post_id/comments/:id', to: 'comments#destroy', as: :delete_comment
  patch '/posts/:post_id/comments/:id', to: 'comments#update', as: :update_comment

  post '/posts/:post_id/comments/:comment_id/reactions', to: 'comment_reactions#create', as: :create_comment_reaction
  delete '/posts/:post_id/comments/:comment_id/reactions/:id', to: 'comment_reactions#destroy', as: :delete_comment_reaction
  
  get 'settings', to: 'settings#edit', as: :settings
  get 'settings/export', to: 'settings#export', as: :export_settings
  get 'settings/exports/:id/download', to: 'settings#download_export', as: :download_export
  patch 'settings/profile', to: 'settings#update_profile', as: :update_profile
  patch 'settings/theme', to: 'settings#update_theme', as: :update_theme
  patch 'settings/access_token', to: 'settings#update_access_token', as: :update_access_token

  get 'privacy/(:locale)', to: 'pages#privacy', as: :privacy
  get 'terms/(:locale)', to: 'pages#terms', as: :terms
  get 'about/(:locale)', to: 'pages#about', as: :about
  get 'docs/(:locale)', to: 'pages#docs', as: :docs

  get '/:username', to: 'users#actor', as: :actor, constraints: lambda { |request| request.format == :json }
  get '/:username', to: 'users#show', as: :user, constraints: lambda { |request| request.format != :json }
  get '/:username/feed', to: 'users#feed', as: :feed
  get 'users/:username' => redirect('/%{username}')
  get '/:username/projects', to: 'projects#index', as: :projects
  get '/:username/projects/list', to: 'projects#list', as: :projects_list
  get '/:username/projects/:codename', to: 'projects#show', as: :project
  get 'projects/new', to: 'projects#new', as: :new_project
  post 'projects', to: 'projects#create', as: :create_project
  get '/:username/projects/:codename/edit', to: 'projects#edit', as: :edit_project
  patch '/:username/projects/:id', to: 'projects#update', as: :update_project
  delete '/:username/projects/:codename', to: 'projects#destroy', as: :delete_project
  post '/:username/follows', to: 'follows#create', as: :follow_user
  delete '/:username/follows', to: 'follows#destroy', as: :unfollow_user
  get '/:username/followers', to: 'users#followers', as: :followers
  get '/:username/following', to: 'users#following', as: :following

  namespace :api do
    namespace :v1 do
      get 'posts', to: 'posts#index', as: :posts
      get 'posts/following', to: 'posts#following', as: :posts_following
      get 'posts/pinned', to: 'posts#pinned', as: :posts_pinned
      get 'posts/:id', to: 'posts#show', as: :post
      post 'posts', to: 'posts#create', as: :create_post
      patch 'posts/:id', to: 'posts#update', as: :update_post
      delete 'posts/:id', to: 'posts#destroy', as: :delete_post
      post 'comments/previews', to: 'comments#preview', as: :preview_comment
      post 'posts/:post_id/comments', to: 'comments#create', as: :create_comment
      patch 'posts/:post_id/comments/:id', to: 'comments#update', as: :update_comment
      delete 'posts/:post_id/comments/:id', to: 'comments#destroy', as: :delete_comment
      post 'projects/previews', to: 'projects#preview', as: :preview_project
      post 'projects', to: 'projects#create', as: :create_project
      patch 'projects/:id', to: 'projects#update', as: :update_project
      delete 'projects/:id', to: 'projects#destroy', as: :delete_project
      post 'posts/preview', to: 'posts#preview', as: :preview_post
      get 'blobs/:id/url', to: 'blobs#url', as: :blob_url
      post 'notifications/read', to: 'notifications#read', as: :read_notifications
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_one_attached :wallpaper
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :post_reactions, dependent: :destroy
  has_many :comment_reactions, dependent: :destroy
  has_many :exports, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :followees, class_name: 'Follow', foreign_key: 'follower_id', dependent: :destroy
  has_many :followers, class_name: 'Follow', foreign_key: 'followee_id', dependent: :destroy
  has_many :followee_users, through: :followees, source: :followee
  has_many :follower_users, through: :followers, source: :follower
  has_many :notifications, dependent: :destroy
  has_many :access_tokens, dependent: :destroy
  has_many :pins, dependent: :destroy
  has_many :cheers, dependent: :destroy
  has_many :cheer_reactions, dependent: :destroy
  belongs_to :code_theme, optional: true

  validates :name, presence: true
  validates :name, exclusion: {
    in: %w(
      posts users sign_in sign_up sign_out confirm register settings comments trending notifications api search pinned latest following notifications rails
      guide help support contact faq docs about privacy terms t
    )
  }
  validates :username, presence: true, uniqueness: true, format: { with: /\A[a-z0-9_]*\z/ }
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: URI::MailTo::EMAIL_REGEXP }
  
  passwordless_with :email

  def username_with_at
    "@#{username}"
  end

  def follow?(user)
    Follow.exists?(follower: self, followee: user)
  end

  def avatar_icon
    if avatar.attached?
      if ENV["CLOUDINARY_CLOUD_NAME"].present? && ENV["CLOUDINARY_API_KEY"].present? && ENV["CLOUDINARY_API_SECRET"].present?
        Cloudinary::Utils.cloudinary_url(avatar.key, width: 150, height: 150, crop: :fill, secure: true)
      else
        avatar
      end
    else
      "https://api.dicebear.com/6.x/thumbs/svg?seed=#{username}"
    end
  end

  def wallpaper_or_none
    if wallpaper.attached?
      wallpaper_url
    else
      no_wallpaper
    end
  end

  def no_wallpaper
    "https://res.cloudinary.com/dw1xpb7if/image/upload/v1691677320/lhr70ktzse7gzw1jtosw.png"
  end

  def wallpaper_url
    if ENV["CLOUDINARY_CLOUD_NAME"].present? && ENV["CLOUDINARY_API_KEY"].present? && ENV["CLOUDINARY_API_SECRET"].present?
      Cloudinary::Utils.cloudinary_url(wallpaper.key, crop: :fill, secure: true)
    else
      wallpaper
    end
  end


  def actor_json
    {
      "@context": "https://www.w3.org/ns/activitystreams",
      type: "Person",
      id: Site.origin + "/#{username}",
      name: username,
      inbox: Site.origin + "/#{username}/inbox",
      outbox: Site.origin + "/#{username}/outbox",
      publicKey: {
        "id": "#{Site.origin}/#{username}#main-key",
        "owner": "#{Site.origin}/#{username}",
        "publicKeyPem": ENV['ACTIVITY_PUB_PUBLIC_KEY']
      },
      icon: {
        type: 'Image',
        mediaType: 'image/png',
        url: avatar_icon
      },
      image: {
        type: 'Image',
        mediaType: 'image/png',
        url: avatar_icon
      }
    }.to_json
  end
end

app/controllers/users_controller.rb
require "bcrypt"
require "rexml/document"

class UsersController < ApplicationController
  include Passwordless::ControllerHelpers

  def header
  end

  def code_theme
  end

  def wallpaper
  end

  def feed
    @user = User.find_by(username: params[:username])
    if @user.nil?
      render file: "#{Rails.root}/public/404.html", status: :not_found
      return
    end
    @posts = @user.posts.joins(:projects).merge(Project.rss).latest
    erb = ERB.new(File.read("#{Rails.root}/app/views/users/feed.xml.erb"))
    render xml: erb.result(binding).html_safe
  end

  def new
    if request.format == "text/html"
      set_cache_control_headers
    end
    @user = User.new
    render :new, layout: "layouts/landing"
  end

  def show
    @user = User.find_by(username: params[:username])
    @post_reaction = PostReaction.new

    if @user.nil?
      render file: "#{Rails.root}/public/404.html", status: :not_found
      return
    end

    page_limit = 20
    @current_page = params[:page].to_i

    all = Post.offset(page_limit*@current_page)
      .where(user_id: @user.id)
      .includes(:user, :comments, :post_reactions)
      .latest
    
    @posts = all.limit(params[:limit] || page_limit)
    @next_page = @current_page + 1 if all.count > page_limit*@current_page + page_limit
  end

  def confirm
    if User.find_by(email: user_params[:email])
      redirect_to "/users/sign_in", flash: { errors: [I18n.t("users.already_registered")] }
      return
    end

    confirm_session = EmailConfirmationSession.new(email: user_params[:email])
    if confirm_session.save
      EmailConfirmationMailer.magic_link(user_params[:email], confirm_session).deliver_now
      redirect_back(
        fallback_location: "/users/sign_up",
        flash: { notice: I18n.t("passwordless.check_your_email") }
      )
    else
      render :new
    end
  end

  def register
    return head(:ok) if request.head?
    BCrypt::Password.create(params[:token])
    confirm_session = EmailConfirmationSession.find_by(token: params[:token])
    @user = User.new(email: confirm_session.email)
    render :register, layout: "layouts/landing"
  rescue Passwordless::Errors::TokenAlreadyClaimedError
    redirect_to sign_up_path, flash: { errors: [I18n.t("passwordless.expired")] }
  rescue Passwordless::Errors::SessionTimedOutError
    redirect_to sign_up_path, flash: { errors: I18n.t("passwordless.expired") }
  end

  def create
    @user = User.new(user_params.merge(locale: I18n.locale))

    if @user.save
      sign_in @user
      redirect_to root_path
    else
      render :register
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])

    if @user != current_user
      render json: { error: "You are not authorized to delete this user." }, status: :unauthorized
      return
    end

    @user.destroy
    redirect_to "/"
  end

  def followers
    @current_page = params[:page].to_i
    @user = User.find_by(username: params[:username])
    all = @user.follower_users
    @followers = all.offset(20*@current_page).limit(20)
    @next_page = @current_page + 1 if all.count > 20*@current_page + 20
  end

  def following
    @current_page = params[:page].to_i
    @user = User.find_by(username: params[:username])
    all = @user.followee_users
    @followees = all.offset(20*@current_page).limit(20)
    @next_page = @current_page + 1 if all.count > 20*@current_page + 20
  end

  private def user_params
    params.require(:user).permit(:email, :username, :name)
  end
end

app/views/users/_follow_nav.html.erb
<nav data-controller="nav">
  <a
    href="<%= following_path(user.username) %>"
    class="<%= nav_item_class(following_path(user.username)) %> mr-5"
    data-turbo-frame="_top"
    data-nav-target="item"
    data-current="<%= following_path(user.username) %>"
  >
    <%= I18n.t("users.following") %>
  </a>
  <a
    href="<%= followers_path(user.username) %>"
    class="<%= nav_item_class(followers_path(user.username)) %> mr-5"
    data-turbo-frame="_top"
    data-nav-target="item"
    data-current="<%= followers_path(user.username) %>"
  >
      <%= I18n.t("users.followers", user: user.name) %>
  </a>
</nav>

app/views/users/_settings.html.erb
<div class="p-4 bg-white dark:bg-dark-card">
  <%= render partial: "shared/error_messages", locals: { errors: @user.errors.full_messages } %>
  <%= render partial: "shared/notice_messages", locals: { notice: notice } %>
  <h2 class="border-b dark:border-gray-600 mb-4 font-bold pb-1"><%= I18n.t("settings.profile") %></h2>
  <%= form_with model: @user, multipart: true, url: update_profile_path, method: :patch, data: { turbo: false } do |f| %>
    <div data-controller="file-field" class="mb-4">
      <%= image_tag @user.avatar_icon, alt: "", width: "100px", height: "100px", class: "w-20 h-20 object-cover rounded-full preview" %>
      <button type="button" class="text-gray-600 inline text-sm hover:bg-gray-100 dark:text-gray-200 dark:hover:bg-gray-700 rounded-full py-1 px-3 mt-3" data-action="file-field#click" >
        <%= I18n.t("form.button.change_file") %>
      </button>
      <%= f.file_field :avatar, data: { file_field_target: "field" }, accept: "image/png, image/jpeg", class: "hidden" %>
    </div>
    <%= f.label :username, class: label_class %>
    <%= f.text_field :username, class: text_field_class + " mb-5" %>
    <%= f.label :name, class: label_class %>
    <%= f.text_field :name, class: text_field_class + " mb-5" %>
    <%= f.label :bio, class: label_class %>
    <%= f.text_area :bio, class: text_field_class + " mb-5", placeholder: I18n.t("form.placeholder.normal", field: User.human_attribute_name(:bio)) %>
    <%= f.label :github, class: label_class %>
    <%= f.text_field :github, class: text_field_class + " mb-5", placeholder: I18n.t("form.placeholder.github") %>
    <%= f.label :twitter, class: label_class %>
    <%= f.text_field :twitter, class: text_field_class + " mb-5", placeholder: I18n.t("form.placeholder.twitter") %>
    <%= f.label :website, class: label_class %>
    <%= f.text_field :website, class: text_field_class + " mb-5", placeholder: "https://" %>
    <div class="flex">
      <%= f.submit I18n.t("form.submit.update"), class: primary_button_class %>
    </div>
  <% end %>
  <h2 class="border-b mt-8 dark:border-gray-600 mb-4 font-bold pb-1"><%= I18n.t("settings.theme") %></h2>
  <%= form_with model: @user, url: update_theme_path, method: :patch, data: { turbo: false }, multipart: true do |f| %>
    <%= f.label :locale, class: label_class %>
    <%= f.select :locale, [:en, :ja].map { |locale| [I18n.t("settings.locale.#{locale}"), locale] }, {}, class: "#{text_field_class} mb-3" %>
    <%= f.label :code_theme_id, class: label_class %>
    <a href="https://highlightjs.org/examples" target="_blank" rel="noopener noreferrer" class="text-sky-600 hover:underline mb-4 flex items-center space-x-2 text-sm">
      <span><%= I18n.t("settings.theme_preview") %></span>
    </a>
    <%= f.select :code_theme_id, CodeTheme.order(:name).map { |theme| [theme.name, theme.id] }, {}, class: "#{text_field_class} mb-3" %>
    <%= f.label :wallpaper, class: label_class %>
    <div data-controller="file-field" data-file-field-fallback-value="<%= current_user.no_wallpaper %>" class="mb-4">
    <%= image_tag @user.wallpaper_or_none, alt: "", class: "w-[400px] h-[220px] object-cover preview rounded" %>
    <button type="button" class="text-gray-600 inline text-sm hover:bg-gray-100 dark:text-gray-200 dark:hover:bg-gray-700 rounded-full py-1 px-3 mt-3" data-action="file-field#click" >
      <%= I18n.t("form.button.change_file") %>
    </button>
    <button type="button" class="text-red-600 inline text-sm hover:bg-gray-100 dark:text-gray-200 dark:hover:bg-gray-700 rounded-full py-1 px-3 mt-3" data-action="file-field#remove" >
      <%= I18n.t("form.submit.delete") %>
    </button>
    <%= f.file_field :wallpaper, data: { file_field_target: "field" }, accept: "image/png, image/jpeg", class: "hidden" %>
    <%= f.hidden_field :no_wallpaper, data: { file_field_target: "fallback" } %>
  </div>
  <div class="flex">
    <%= f.submit I18n.t("form.submit.update"), class: primary_button_class %>
  </div>
  <% end %>
  <h2 class="border-b mt-8 dark:border-gray-600 mb-4 font-bold pb-1"><%= I18n.t("settings.export") %></h2>
  <div class="text-left text-sm">
    <% if current_user.exports.find_by(state: "processing") %>
      <%= I18n.t("settings.exporting") %>
    <% else %>
      <%= link_to(
        "/settings/export",
        data: { turbo: false },
        class: primary_button_class + " inline-flex items-center space-x-1",
      ) do %>
        <%= I18n.t("settings.start_export") %>
      <% end %>
    <% end %>
  </div>
  <h2 class="border-b mt-8 dark:border-gray-600 mb-4 font-bold pb-1"><%= I18n.t("settings.api") %></h2>
  <%= form_with model: @user, url: update_access_token_path, method: :patch, data: { turbo: false }, class: "mb-4" do |f| %>
    <%= f.label :access_token, class: label_class %>
    <%= f.text_field :access_token, class: text_field_class + " mb-5", readonly: true, value: current_user.access_tokens.first&.token %>
    <div class="flex items-center space-x-2">
      <button type="button" data-controller="copy" data-copy-copied-text-value="<%= I18n.t("clipboard.copied") %>" data-copy-content-value="<%= current_user.access_tokens.first&.token %>" class="<%= block_link_class %>  flex items-center space-x-1" >
        <div class="i-lucide-clipboard-copy"></div>
        <span><%= I18n.t("settings.copy") %></span>
      </button>
      <%= f.submit current_user.access_tokens.first&.token ? I18n.t("settings.access_token.regenerate") : I18n.t("settings.access_token.generate"), class: primary_button_class, onclick: "#{ current_user.access_tokens.first&.token ? "return confirm('#{I18n.t("settings.access_token.confirm")}')" : ""}" %>
    </div>
  <% end %>
  <h2 class="border-b mt-8 dark:border-gray-600 mb-4 font-bold pb-1"><%= I18n.t("settings.account") %></h2>
  <div class="text-left text-sm">
    <%= button_to I18n.t("passwordless.sessions.sign_out"), "/sign_out", data: { turbo: false }, method: :delete %>
  </div>
  <h2 class="border-b mt-8 dark:border-gray-600 mb-4 font-bold pb-1">Danger Zone</h2>
  <div class="text-left text-sm">
    <%= button_to(
      I18n.t("users.delete"),
      "/users/#{current_user.id}",
      data: { turbo: false },
      onClick: "return confirm('#{I18n.t("users.confirm_delete")}');",
      method: :delete,
      class: "text-red-500",
      
    ) %>
  </div>
</div>

app/views/users/_user_nav.html.erb
<nav data-controller="nav">
  <a
    href="<%= user_path(user.username) %>"
    class="<%= nav_item_class(user_path(user.username)) %> mr-5"
    data-turbo-frame="_top"
    data-testid="view-posts"
    role="tab"
    data-nav-target="item"
    data-current="<%= user_path(user.username) %>"
    aria-controls="posts"
  >
    <%= I18n.t("pages.posts") %>
  </a>
  <a
    href="<%= projects_path(user.username) %>"
    class="<%= nav_item_class(projects_path(user.username)) %> mr-5"
    data-turbo-frame="_top"
    role="tab"
    data-nav-target="item"
    data-current="<%= projects_path(user.username) %>"
    aria-controls="projects"
    data-testid="view-projects"
  >
    <%= I18n.t("users.projects", user: user.name) %>
  </a>
</nav>

app/views/users/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Users#create</h1>
  <p>Find me in app/views/users/create.html.erb</p>
</div>

app/views/users/feed.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title><%= REXML::Document.new.tap { |doc| doc.add(REXML::CData.new("Timesy/#{@user.name}")) } %></title>
    <description><%= REXML::Document.new.tap { |doc| doc.add(REXML::CData.new("Timesyの#{@user.name}さんのフィード")) } %></description>
    <link><%= user_url(@user.username) %></link>
    <language>ja</language>
    <lastBuildDate><%= @posts.first ? @posts.first.updated_at.to_s(:rfc822) : @user.created_at.to_s(:rfc822) %></lastBuildDate>
    <generator>Timesy</generator>
    <image>
      <url>https://timesy.dev/logo.png</url>
      <title><%= REXML::Document.new.tap { |doc| doc.add(REXML::CData.new("Timesy/#{@user.name}")) }.to_s %></title>
      <link><%= user_url(@user.username) %></link>
    </image>
    <atom:link rel="self" type="application/rss+xml" href="<%= feed_url(@user.username) %>"/>
    <% @posts.each do |p| %>
      <item>
        <title><%= REXML::CData.new(p.truncated.gsub("&lt;", '').gsub("&gt;", '')) %></title>
        <description><%= REXML::CData.new(p.truncated(256).gsub("&lt;", '').gsub("&gt;", '')) %></description>
        <pubDate><%= p.updated_at.to_s(:rfc822) %></pubDate>
        <link><%= post_url(p) %></link>
        <guid><%= post_url(p) %></guid>
        <enclosure url="https://www.timesy.dev/landing.jpg" type="image/jpeg" length="0" />
        <% p.projects.each do |proj| %>
          <category domain="<%= project_url(@user.username, proj) %>">
            <%= REXML::Document.new.tap { |doc| doc.add(REXML::CData.new(proj.title)) }.to_s %>
          </category>
        <% end %>
        <dc:creator><%= @user.name %></dc:creator>
      </item>
    <% end %>
  </channel>
</rss>

app/views/users/followers.html.erb
<% set_meta_tags(
  title: I18n.t("pages.followers", user: @user.name),
  og: {
    title: I18n.t("pages.followers", user: @user.name),
  }
) %>

<div class="w-full max-w-3xl mx-auto p-0 sm:p-4">
  <div id="profile-<%= @user.id %>" data-turbo-permanent>
    <%= render partial: "users/profile", locals: { user: @user } %>
  </div>
  <div id="follow-nav-container" class="top-0 sticky z-[50]" data-turbo-permanent>
    <div class="<%= nav_class %>">
      <div class="<%= nav_list_class %>">
        <%= render partial: "users/follow_nav", locals: { user: @user } %>
      </div>
    </div>
  </div>
  <div class="max-w-3xl mx-auto">
    <%= turbo_frame_tag :users do %>
    <% end %>

    <div class="h-4">
      <%= turbo_frame_tag "load_more", src: followers_path(username: @user.username, format: :turbo_stream), loading: :lazy %>
      <%= turbo_frame_tag "loading" do %>
        <%= render partial: "shared/loading" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.turbo_stream.erb
<%= turbo_stream.append "users" do %>
  <div data-testid="follower-list">
    <%= render partial: 'users/item', collection: @followers %>
  </div>
<% end %>

<% if @next_page.present? %>
  <%= turbo_stream.replace "load_more" do %>
    <%= turbo_frame_tag "load_more", src: followers_path(username: @user.username, page: @next_page, format: :turbo_stream), loading: :lazy %>
  <% end %>
<% else %>
  <%= turbo_stream.replace "loading" do %>
  <% end %>
<% end %>

app/views/users/following.html.erb
<% set_meta_tags(
  title: I18n.t("pages.following", user: @user.name),
  og: {
    title: I18n.t("pages.following", user: @user.name),
  }
) %>

<div class="w-full max-w-3xl mx-auto p-0 sm:p-4">
  <div id="profile-<%= @user.id %>" data-turbo-permanent>
    <%= render partial: "users/profile", locals: { user: @user } %>
  </div>
  <div id="follow-nav-container" class="top-0 sticky z-[50]" data-turbo-permanent>
    <div class="<%= nav_class %>">
      <div class="<%= nav_list_class %>">
        <%= render partial: "users/follow_nav", locals: { user: @user } %>
      </div>
    </div>
  </div>
  <div class="max-w-3xl mx-auto">
    <%= turbo_frame_tag :users do %>
    <% end %>

    <div class="h-4">
      <%= turbo_frame_tag "load_more", src: following_path(username: @user.username, format: :turbo_stream), loading: :lazy %>
      <%= turbo_frame_tag "loading" do %>
        <%= render partial: "shared/loading" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/following.turbo_stream.erb
<%= turbo_stream.replace "loading" do %>
<% end %>

<%= turbo_stream.append "users" do %>
  <div data-testid="following-list">
    <%= render partial: 'users/item', collection: @followees %>
  </div>
<% end %>

<% if @next_page.present? %>
  <%= turbo_stream.replace "load_more" do %>
    <%= turbo_frame_tag "load_more", src: following_path(username: @user.username, page: @next_page, format: :turbo_stream), loading: :lazy %>
  <% end %>
<% end %>

app/views/users/show.html.erb
<% content_for(:rss_meta_tags) do %>
  <link href="<%= feed_url(@user.username) %>" rel="alternate" title="Timesy/<%= @user.name %>" type="application/rss+xml">
<% end %>

<% set_meta_tags(
  title: @user.name,
  og: {
    title: @user.name
  },
  twitter: {
    card: "summary",
    image: @user.avatar_icon
  }
) %>

<%= turbo_frame_tag "timeline" do %>
<div class="max-w-3xl mx-auto p-4">
  <div id="profile-<%= @user.id %>" data-turbo-permanent>
    <%= render partial: "users/profile", locals: { user: @user } %>
  </div>
  <div id="user-nav-container" class="z-[50]" data-turbo-permanent>
    <div class="<%= nav_class %>">
      <div class="<%= nav_list_class %>">
        <%= render partial: "users/user_nav", locals: { user: @user } %>
      </div>
    </div>
  </div>
  <div>
    <%= turbo_frame_tag "users_posts", target: "_top" do %>
    <% end %>

    <div class="h-4">
      <%= turbo_frame_tag "usres_load_more", src: user_path(username: @user.username, format: :turbo_stream), loading: :lazy %>
      <%= turbo_frame_tag "users_loading" do %>
        <%= render partial: "shared/loading" %>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/users/show.turbo_stream.erb
<%= turbo_stream.append "users_posts" do %>
  <% if @posts.present? %>
    <div data-testid="post-list">
      <%= render partial: "posts/post", collection: @posts, locals: { additional_class: "mb-4", on_timeline: true } %>
    </div>
  <% else %>
    <%= turbo_stream.replace "users_loading" do %>
    <% end %>
  <% end %>
<% end %>

<% if @next_page.present? && !params[:limit].present? %>
  <%= turbo_stream.replace "users_load_more" do %>
    <%= turbo_frame_tag "users_load_more", src: user_path(username: @user.username, page: @next_page, format: :turbo_stream), loading: :lazy %>
  <% end %>
<% else %>
  <%= turbo_stream.replace "users_loading" do %>
  <% end %>
  <%= turbo_stream.replace "users_load_more" do %>
  <% end %>
<% end %>