config/routes.rb
Rails.application.routes.draw do
  passwordless_for :users, at: '/'

  get 'notifications/index'

  get "t/sitemap", to: "sitemap#index", as: :sitemap, defaults: { format: "xml" }

  get 'sign_up', to: 'users#new', as: :sign_up
  post 'users/confirm', to: 'users#confirm', as: :confirm
  get 'users/register/:token', to: 'users#register', as: :register
  post 'users', to: 'users#create', as: :create_user
  delete 'users/:id', to: 'users#destroy', as: :delete_user

  get '/notifications', to: 'notifications#index', as: :notifications

  root 'posts#index'
  get "/latest", to: "posts#latest", as: :latest
  get "/pinned", to: "posts#pinned", as: :pinned
  get "posts/:id", to: "posts#show", as: :post
  post "posts", to: "posts#create", as: :create_post
  patch "posts/:id", to: "posts#update", as: :update_post
  delete "posts/:id", to: "posts#destroy", as: :delete_post
  get '/posts/:id/pin_button', to: 'posts#pin_button', as: :post_pin_button

  post '/posts/:post_id/pins', to: 'pins#create', as: :create_pin
  delete '/posts/:post_id/pins/:id', to: 'pins#destroy', as: :delete_pin

  get '/posts/:post_id/reactions', to: 'post_reactions#index', as: :post_reactions
  post '/posts/:post_id/reactions', to: 'post_reactions#create', as: :create_post_reaction
  delete '/posts/:post_id/reactions/:id', to: 'post_reactions#destroy', as: :delete_post_reaction

  get '/posts/:post_id/comments', to: 'comments#index', as: :comments
  post '/posts/:post_id/comments', to: 'comments#create', as: :create_comment
  delete '/posts/:post_id/comments/:id', to: 'comments#destroy', as: :delete_comment
  patch '/posts/:post_id/comments/:id', to: 'comments#update', as: :update_comment

  post '/posts/:post_id/comments/:comment_id/reactions', to: 'comment_reactions#create', as: :create_comment_reaction
  delete '/posts/:post_id/comments/:comment_id/reactions/:id', to: 'comment_reactions#destroy', as: :delete_comment_reaction
  
  get 'settings', to: 'settings#edit', as: :settings
  get 'settings/export', to: 'settings#export', as: :export_settings
  get 'settings/exports/:id/download', to: 'settings#download_export', as: :download_export
  patch 'settings/profile', to: 'settings#update_profile', as: :update_profile
  patch 'settings/theme', to: 'settings#update_theme', as: :update_theme
  patch 'settings/access_token', to: 'settings#update_access_token', as: :update_access_token

  get 'privacy/(:locale)', to: 'pages#privacy', as: :privacy
  get 'terms/(:locale)', to: 'pages#terms', as: :terms
  get 'about/(:locale)', to: 'pages#about', as: :about
  get 'docs/(:locale)', to: 'pages#docs', as: :docs

  get '/:username', to: 'users#actor', as: :actor, constraints: lambda { |request| request.format == :json }
  get '/:username', to: 'users#show', as: :user, constraints: lambda { |request| request.format != :json }
  get '/:username/feed', to: 'users#feed', as: :feed
  get 'users/:username' => redirect('/%{username}')
  get '/:username/projects', to: 'projects#index', as: :projects
  get '/:username/projects/list', to: 'projects#list', as: :projects_list
  get '/:username/projects/:codename', to: 'projects#show', as: :project
  get 'projects/new', to: 'projects#new', as: :new_project
  post 'projects', to: 'projects#create', as: :create_project
  get '/:username/projects/:codename/edit', to: 'projects#edit', as: :edit_project
  patch '/:username/projects/:id', to: 'projects#update', as: :update_project
  delete '/:username/projects/:codename', to: 'projects#destroy', as: :delete_project
  post '/:username/follows', to: 'follows#create', as: :follow_user
  delete '/:username/follows', to: 'follows#destroy', as: :unfollow_user
  get '/:username/followers', to: 'users#followers', as: :followers
  get '/:username/following', to: 'users#following', as: :following

  namespace :api do
    namespace :v1 do
      get 'posts', to: 'posts#index', as: :posts
      get 'posts/following', to: 'posts#following', as: :posts_following
      get 'posts/pinned', to: 'posts#pinned', as: :posts_pinned
      get 'posts/:id', to: 'posts#show', as: :post
      post 'posts', to: 'posts#create', as: :create_post
      patch 'posts/:id', to: 'posts#update', as: :update_post
      delete 'posts/:id', to: 'posts#destroy', as: :delete_post
      post 'comments/previews', to: 'comments#preview', as: :preview_comment
      post 'posts/:post_id/comments', to: 'comments#create', as: :create_comment
      patch 'posts/:post_id/comments/:id', to: 'comments#update', as: :update_comment
      delete 'posts/:post_id/comments/:id', to: 'comments#destroy', as: :delete_comment
      post 'projects/previews', to: 'projects#preview', as: :preview_project
      post 'projects', to: 'projects#create', as: :create_project
      patch 'projects/:id', to: 'projects#update', as: :update_project
      delete 'projects/:id', to: 'projects#destroy', as: :delete_project
      post 'posts/preview', to: 'posts#preview', as: :preview_post
      get 'blobs/:id/url', to: 'blobs#url', as: :blob_url
      post 'notifications/read', to: 'notifications#read', as: :read_notifications
    end
  end
end

app/views/shared/_activities.erb
<div class="flex w-full max-w-3xl overflow-hidden">
  <div class="pt-[18px]">
    <div class="flex pt-[14px] flex-col h-[130px] text-xs pr-[2px] text-right">
      <div class="h-[32px]">Mon</div>
      <div class="h-[32px]">Wed</div>
      <div class="h-[32px]">Fri</div>
    </div>
  </div>
  <div class="w-full max-w-full overflow-scroll">
    <div class="flex flex-col h-[130px] w-[832px] flex-wrap">
      <% score_per_day = Post.score_per_day(user) %>
      <% (Date.new(year.to_i, 1, 1).beginning_of_year..Date.new(year.to_i, 1, 1).end_of_year).each_with_index do |date, i| %>
        <% if date.sunday? %>
          <% if date.day < 8 %>
            <div class="h-[16px] w-[16px] p-[2px] text-xs mb-[2px]">
              <%= date.strftime("%b") %>
            </div>
          <% else %>
            <div class="h-[16px] w-[16px] p-[2px] mb-[2px]">
            </div>
          <% end %>
        <% end %>
        <% if i == 0 %>
          <% if !date.sunday? %>
            <div class="h-[16px] w-[16px] p-[2px] mb-[2px]">
            </div>
          <% end %>
          <% (Date.new(year.to_i, 1, 1).wday).times do |date| %>
            <div class="h-[16px] w-[16px] p-[2px]">
              <div class="h-[12px] w-[12px]"></div>
            </div>
          <% end %>
        <% end %>
        <div class="h-[16px] w-[16px] p-[2px]">
          <div class="h-[12px] w-[12px] rounded-sm cell <%= "cell-#{score_per_day[date] ? score_per_day[date] : "0"}" %>"></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_avatar.html.erb
<%= link_to user_path(username: user.username), class: " text-sm block flex items-center hover:underline flex-wrap", data: { turbo_frame: "_top" } do %>
  <%= image_tag user.avatar_icon, alt: "", width: "20px", height: "20px", class: "w-8 h-8 rounded-full mr-2 block" %>
  <span class="mr-1 font-bold"><%= user.name %></span>
  <span class="text-gray-400"><%= user.username_with_at %></span>
<% end %>

app/views/shared/_code_block.html.erb
<div class="top-7 right-6 absolute  hidden opacity-50" data-code-block-target='button'>
  <button data-action="code-block#copy" class="text-lg absolute top-0 left-0 w-8 h-8 opacity-50 bg-gray-400 hover:bg-gray-500 rounded transition-all animate-fade-in p-4" >
    <i class="block i-lucide-copy absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2"></i>
  </button>
</div>
<%= code.html_safe %>

app/views/shared/_error_messages.html.erb
<% if errors.present? && errors.is_a?(Array) %>
  <div class="mb-5">
    <ul class="bg-red-100 text-xs list-disc border border-red-600 rounded py-2 px-6" >
    <% errors.each do |error| %>
      <li class="text-red-600"><%= error %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_follows.html.erb
<div class="flex items-center space-x-2">
  <%= link_to following_path(user.username), class: "text-sm hover:underline", data: { turbo_frame: "_top", testid: "view-following" } do %>
    <span class="font-bold">
      <%= user.followee_users.count %>
    </span>
    <%= I18n.t("users.following") %>
  <% end %>
  <%= link_to followers_path(user.username), class: "text-sm hover:underline", data: { turbo_frame: "_top", testid: "view-followers" } do %>
    <span class="font-bold">
      <%= user.follower_users.count %>
    </span>
    <%= I18n.t("users.followers") %>
  <% end %>
</div>

app/views/shared/_head.html.erb
<head>
  <%= display_meta_tags(default_meta_tags)%>
  <meta name="description" content="<%= Site.description %>">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/easymde/dist/easymde.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
    rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/hyrious/github-markdown-css@main/dist/light.css" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet"
      href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/default.min.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Color+Emoji&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://unpkg.com/tippy.js@6/themes/light.css" />
  <link rel="stylesheet" href="https://unpkg.com/tippy.js@6/dist/backdrop.css" />
  <link rel="stylesheet" href="https://unpkg.com/tippy.js@6/animations/shift-away.css" />
  
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
  <script src="https://unpkg.com/@popperjs/core@2"></script>
  <script src="https://unpkg.com/tippy.js@6"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js"></script>
  <script>
    hljs.highlightAll();
    const mo = new MutationObserver(() => {
      hljs.highlightAll();
    })
    mo.observe(document.documentElement, { childList: true });
    document.documentElement.addEventListener('turbo:frame-render', () => {
      hljs.highlightAll();
    })
  </script>
</head>

app/views/shared/_header.html.erb
<header class="w-full bg-white shadow-sm rounded-t-lg">
  <div class="flex px-5 items-center py-3 text-sm max-w-5xl mx-auto">
    <%= link_to "/", class: "block mr-3" do %>
      <img src="<%= "/logo.png" %>" alt="logo" width="70px" height="20px" />
    <% end %>
    <div class="grow"></div>
    <% if current_user %>
      <%= link_to user_path(username: current_user.username) do %>
        <%= image_tag current_user.avatar_icon, alt: current_user.username, class: "w-8 h-8 object-cover rounded-full" %>
      <% end %>
    <% else %>
      <%= link_to I18n.t("users.sign_in"), "/users/sign_in", class: "mr-2 rounded hover:bg-gray-50 py-1 px-2" %>
      <%= link_to I18n.t("users.sign_up"), "/users/sign_up", class: primary_button_class %>
    <% end %>
  <div>
</header>

app/views/shared/_link_card.html.erb
<div class="link-card  overflow-hidden w-full rounded shadow-sm">
<a href="<%= ogp.url %>" data-turbo-frame="_top">
  <% if ogp.image.present? %>
    <img src="<%= ogp.image %>" class="object-cover border-b dark:border-dark-border" alt="">
  <% end %>
  <div class="grow p-4">
    <div class="opacity-50"><%= ogp.host %></div>
    <div class="text-sm"><%= ogp.truncated_title %></div>
    <div class="text-xs text-gray-500"><%= ogp.truncated_description %></div>
  </div>
</a>
</div>

app/views/shared/_loading.html.erb
<div class="shadow-sm transition-all p-4 w-full mx-auto mb-4 dark:border-dark-border border-b bg-white dark:bg-dark-card opacity-70">
  <div class="animate-pulse flex space-x-4">
    <div class="rounded-full bg-slate-200 dark:bg-gray-800 h-8 w-8"></div>
    <div class="flex-1 space-y-6 py-1">
      <div class="h-2 bg-slate-200 dark:bg-gray-800 rounded"></div>
      <div class="space-y-3">
        <div class="grid grid-cols-3 gap-4">
          <div class="h-2 bg-slate-200 dark:bg-gray-800 rounded col-span-2"></div>
          <div class="h-2 bg-slate-200 dark:bg-gray-800 rounded col-span-1"></div>
        </div>
        <div class="h-2 bg-slate-200 dark:bg-gray-800 rounded"></div>
        <div class="h-2 bg-slate-200 dark:bg-gray-800 rounded"></div>
        <div class="grid grid-cols-3 gap-4">
          <div class="h-2 bg-slate-200 dark:bg-gray-800 rounded col-span-2"></div>
          <div class="h-2 bg-slate-200 dark:bg-gray-800 rounded col-span-1"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_mini_avatar.html.erb
<%= link_to user_path(username: user.username), class: " text-sm block flex items-center hover:underline flex-wrap", data: { turbo_frame: "_top" } do %>
  <%= image_tag user.avatar_icon, alt: "", width: "10px", height: "10px", class: "w-4 h-4 rounded-full mr-1 block" %>
  <span class="text-gray-400 text-sm"><%= user.username_with_at %></span>
<% end %>

app/views/shared/_notice_messages.html.erb
<% if flash[:notice] %>
  <div class="mb-5">
    <div class="text-xs text-sky-600 bg-sky-100 border border-sky-600 rounded py-2 px-2" role="alert">
      <%= flash[:notice] %>
    </div>
  </div>
<% end %>

app/views/shared/_pin_button.html.erb
<div data-post-show-target="menu">
<% if post.pinned_by?(current_user) %>
  <%= button_to delete_pin_path(post.id, Pin.find_by(user: current_user, post: post)), class: "#{block_link_class} text-sky-500 dark:text-sky-500 w-full", method: :delete do %>
    <div class="i-lucide-pin"></div>
    <%= I18n.t("posts.pinned") %>
  <% end %>
<% else %>
  <%= button_to create_pin_path(post_id: post.id), method: :post, class: "#{block_link_class} w-full" do %>
    <div class="i-lucide-pin "></div>
    <%= I18n.t("posts.pin") %>
  <% end %>
<% end %>
</div>

app/views/shared/_sidebar.html.erb
<div class="relative  hidden <%= should_render_sidebar? ? "md:block" : "md:hidden" %>">
  <div class="sticky text-sm top-4 bg-white shadow-sm rounded-lg w-64 p-4">
    <ul class="mb-4 flex flex-col">
      <li>
        <%= link_to I18n.t("pages.latest"), latest_path, class: "#{request.path === latest_path ? "font-bold" : ""} py-1 px-2 block hover:bg-gray-50 rounded" %>
      </li>
      <% if current_user %>
      <li>
        <%= link_to I18n.t("pages.follow"), root_path, class: "#{request.path === root_path ? "font-bold" : ""} py-1 px-2 block hover:bg-gray-50 rounded" %>
      </li>
      <li>
        <%= link_to I18n.t("pages.your_posts"), user_path(current_user.username), class: "#{request.path === user_path(current_user.username) ? "font-bold" : ""} py-1 px-2 block hover:bg-gray-50 rounded" %>
      </li>
      <li>
        <%= link_to I18n.t("pages.your_comments"), user_comments_path(current_user.username), class: "#{request.path === user_comments_path(current_user.username) ? "font-bold" : ""} py-1 px-2 block hover:bg-gray-50 rounded" %>
      </li>
      <li>
        <%= link_to I18n.t("pages.your_projects"), projects_path(current_user.username), class: "#{request.path === projects_path(current_user.username) ? "font-bold" : ""} py-1 px-2 block hover:bg-gray-50 rounded" %>
      </li>
      <li>
        <%= link_to I18n.t("pages.settings"), settings_path, class: "#{request.path === settings_path ? "font-bold" : ""} py-1 px-2 block hover:bg-gray-50 rounded" %>
      </li>
      <% end %>
      <li class="w-full border-b pb-2"></li>
      <li class="w-full pb-2"></li>
      <li>
        <%= link_to I18n.t("pages.docs"), docs_path, class: "#{request.path === docs_path ? "font-bold" : ""} py-1 px-2 block hover:bg-gray-50 rounded" %>
      </li>
      <li>
        <%= link_to I18n.t("pages.about"), about_path, class: "#{request.path === about_path ? "font-bold" : ""} py-1 px-2 block hover:bg-gray-50 rounded" %>
      </li>
      <li>
        <%= link_to I18n.t("pages.terms"), terms_path, class: "#{request.path === terms_path ? "font-bold" : ""} py-1 px-2 block hover:bg-gray-50 rounded" %>
      </li>
      <li>
        <%= link_to I18n.t("pages.privacy"), privacy_path, class: "#{request.path === privacy_path ? "font-bold" : ""} py-1 px-2 block hover:bg-gray-50 rounded" %>
      </li>
      <li>
        <%= link_to "https://forms.gle/7FZz2iHzYLQYiom7A", class: " py-1 px-2 block hover:bg-gray-50 rounded", target: "_blank" do %>
          <span><%= I18n.t("pages.emoji_request") %></span>
          <%= image_tag "icons/newtab.svg", class: "inline-block h-3 w-3 pb-[1px] ml-[1px]" %>
        <% end %>
      </li>
      <li>
        <%= link_to "https://github.com/moekidev/timesy", class: " py-1 px-2 block hover:bg-gray-50 rounded", target: "_blank" do %>
          <span><%= I18n.t("pages.github") %></span>
          <%= image_tag "icons/newtab.svg", class: "inline-block h-3 w-3 pb-[1px] ml-[1px]" %>
        <% end %>
      </li>
      <li>
        <%= link_to "https://status.timesy.dev/", class: " py-1 px-2 block hover:bg-gray-50 rounded", target: "_blank" do %>
          <span><%= I18n.t("pages.status") %></span>
          <%= image_tag "icons/newtab.svg", class: "inline-block h-3 w-3 pb-[1px] ml-[1px]" %>
        <% end %>
      </li>
      <li>
        <%= link_to "https://www.buymeacoffee.com/moekidev", class: " py-1 px-2 block hover:bg-gray-50 rounded", target: "_blank" do %>
          <span><%= I18n.t("pages.tip") %></span>
          <%= image_tag "icons/newtab.svg", class: "inline-block h-3 w-3 pb-[1px] ml-[1px]" %>
        <% end %>
      </li>
    </ul>
    <div>
      <p class="text-right text-gray-500 font-normal text-xs">
        &copy; 2023 Timesy
      </p>
    </div>
  </div>
</div>

app/views/shared/_tweet_card.html.erb
<blockquote class="twitter-tweet"><a href="<%= url %>"></a></blockquote>