config/routes.rb
Rails.application.routes.draw do
  passwordless_for :users, at: '/'

  get 'notifications/index'

  get "t/sitemap", to: "sitemap#index", as: :sitemap, defaults: { format: "xml" }

  get 'sign_up', to: 'users#new', as: :sign_up
  post 'users/confirm', to: 'users#confirm', as: :confirm
  get 'users/register/:token', to: 'users#register', as: :register
  post 'users', to: 'users#create', as: :create_user
  delete 'users/:id', to: 'users#destroy', as: :delete_user

  get '/notifications', to: 'notifications#index', as: :notifications

  root 'posts#index'
  get "/latest", to: "posts#latest", as: :latest
  get "/pinned", to: "posts#pinned", as: :pinned
  get "posts/:id", to: "posts#show", as: :post
  post "posts", to: "posts#create", as: :create_post
  patch "posts/:id", to: "posts#update", as: :update_post
  delete "posts/:id", to: "posts#destroy", as: :delete_post
  get '/posts/:id/pin_button', to: 'posts#pin_button', as: :post_pin_button

  post '/posts/:post_id/pins', to: 'pins#create', as: :create_pin
  delete '/posts/:post_id/pins/:id', to: 'pins#destroy', as: :delete_pin

  get '/posts/:post_id/reactions', to: 'post_reactions#index', as: :post_reactions
  post '/posts/:post_id/reactions', to: 'post_reactions#create', as: :create_post_reaction
  delete '/posts/:post_id/reactions/:id', to: 'post_reactions#destroy', as: :delete_post_reaction

  get '/posts/:post_id/comments', to: 'comments#index', as: :comments
  post '/posts/:post_id/comments', to: 'comments#create', as: :create_comment
  delete '/posts/:post_id/comments/:id', to: 'comments#destroy', as: :delete_comment
  patch '/posts/:post_id/comments/:id', to: 'comments#update', as: :update_comment

  post '/posts/:post_id/comments/:comment_id/reactions', to: 'comment_reactions#create', as: :create_comment_reaction
  delete '/posts/:post_id/comments/:comment_id/reactions/:id', to: 'comment_reactions#destroy', as: :delete_comment_reaction
  
  get 'settings', to: 'settings#edit', as: :settings
  get 'settings/export', to: 'settings#export', as: :export_settings
  get 'settings/exports/:id/download', to: 'settings#download_export', as: :download_export
  patch 'settings/profile', to: 'settings#update_profile', as: :update_profile
  patch 'settings/theme', to: 'settings#update_theme', as: :update_theme
  patch 'settings/access_token', to: 'settings#update_access_token', as: :update_access_token

  get 'privacy/(:locale)', to: 'pages#privacy', as: :privacy
  get 'terms/(:locale)', to: 'pages#terms', as: :terms
  get 'about/(:locale)', to: 'pages#about', as: :about
  get 'docs/(:locale)', to: 'pages#docs', as: :docs

  get '/:username', to: 'users#actor', as: :actor, constraints: lambda { |request| request.format == :json }
  get '/:username', to: 'users#show', as: :user, constraints: lambda { |request| request.format != :json }
  get '/:username/feed', to: 'users#feed', as: :feed
  get 'users/:username' => redirect('/%{username}')
  get '/:username/projects', to: 'projects#index', as: :projects
  get '/:username/projects/list', to: 'projects#list', as: :projects_list
  get '/:username/projects/:codename', to: 'projects#show', as: :project
  get 'projects/new', to: 'projects#new', as: :new_project
  post 'projects', to: 'projects#create', as: :create_project
  get '/:username/projects/:codename/edit', to: 'projects#edit', as: :edit_project
  patch '/:username/projects/:id', to: 'projects#update', as: :update_project
  delete '/:username/projects/:codename', to: 'projects#destroy', as: :delete_project
  post '/:username/follows', to: 'follows#create', as: :follow_user
  delete '/:username/follows', to: 'follows#destroy', as: :unfollow_user
  get '/:username/followers', to: 'users#followers', as: :followers
  get '/:username/following', to: 'users#following', as: :following

  namespace :api do
    namespace :v1 do
      get 'posts', to: 'posts#index', as: :posts
      get 'posts/following', to: 'posts#following', as: :posts_following
      get 'posts/pinned', to: 'posts#pinned', as: :posts_pinned
      get 'posts/:id', to: 'posts#show', as: :post
      post 'posts', to: 'posts#create', as: :create_post
      patch 'posts/:id', to: 'posts#update', as: :update_post
      delete 'posts/:id', to: 'posts#destroy', as: :delete_post
      post 'comments/previews', to: 'comments#preview', as: :preview_comment
      post 'posts/:post_id/comments', to: 'comments#create', as: :create_comment
      patch 'posts/:post_id/comments/:id', to: 'comments#update', as: :update_comment
      delete 'posts/:post_id/comments/:id', to: 'comments#destroy', as: :delete_comment
      post 'projects/previews', to: 'projects#preview', as: :preview_project
      post 'projects', to: 'projects#create', as: :create_project
      patch 'projects/:id', to: 'projects#update', as: :update_project
      delete 'projects/:id', to: 'projects#destroy', as: :delete_project
      post 'posts/preview', to: 'posts#preview', as: :preview_post
      get 'blobs/:id/url', to: 'blobs#url', as: :blob_url
      post 'notifications/read', to: 'notifications#read', as: :read_notifications
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  include Markdownable

  belongs_to :user
  has_and_belongs_to_many :posts
  has_one_attached :icon
  has_many_attached :images

  validates :title, presence: true
  validates :codename, presence: true, uniqueness: true, format: { with: /\A[a-z0-9_]*\z/ }
  validates :link, url: { allow_blank: true }

  scope :latest, -> { order(updated_at: :desc) }
  scope :rss, -> { where(rss: true) }

  def icon_url
    if icon.attached?
      if ENV["CLOUDINARY_CLOUD_NAME"].present? && ENV["CLOUDINARY_API_KEY"].present? && ENV["CLOUDINARY_API_SECRET"].present?
        Cloudinary::Utils.cloudinary_url(icon.key, width: 150, height: 150, crop: :fill)
      else
        icon
      end
    else
      "https://api.dicebear.com/6.x/shapes/svg?seed=#{codename}"
    end
  end
end

app/controllers/api/v1/projects_controller.rb
module Api
  module V1
    class ProjectsController < ApplicationController
      before_action :authenticate_user!, only: [:create, :update, :destroy]
      skip_forgery_protection

      def preview
        @project = Project.new(body: project_params[:body])
        render json: { body: @project.html.html_safe }
      end

      def create
        @project = Project.new(project_params)
        @project.user = current_user
        @project.save
        render json: { project: ProjectSerializer.render_as_hash(@project) }
      end

      def update
        @project = Project.find(params[:id])
        if @project.user != current_user
          render json: { error: "You are not authorized to edit this project." }, status: 401
          return
        end
        @project.update(project_params)
        render json: { project: ProjectSerializer.render_as_hash(@project) }
      end

      def destroy
        @project = Project.find(params[:id])
        if @project.user != current_user
          render json: { error: "You are not authorized to delete this project." }, status: 401
          return
        end
        @project.destroy
        render json: {}, status: 204
      end

      private def project_params
        params.require(:project).permit(:title, :body, :link, :codename)
      end
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def list
    @user = User.find_by(username: params[:username])
    @projects = Project.where(user_id: @user.id)
  end

  def index
    @user = User.find_by(username: params[:username])
    @current_page = params[:page].to_i
    all_projects = Project.offset(page_limit*@current_page)
      .latest
      .where(user_id: @user.id)
    
    if params[:limit] || page_limit
      @projects = all_projects.limit(params[:limit] || page_limit)
    else
      @projects = all_projects
    end
    @next_page = @current_page + 1 if all_projects.count > page_limit*@current_page + page_limit
  end

  def show
    @user = User.find_by(username: params[:username])
    @project = Project.find_by(user_id: @user.id, codename: params[:codename])
    @current_page = params[:page].to_i

    if @project.nil?
      redirect_to projects_path(@user.username)
      return
    end

    @posts = @project.posts.offset(page_limit*@current_page)
      .order(updated_at: :desc)
      .limit(page_limit)
    @next_page = @current_page + 1 if Post.all.count > page_limit*@current_page + page_limit
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    if @project.save
      redirect_to project_path(@project.user.username, @project.codename)
    else
      render :new
    end
  end

  def edit
    @user = User.find_by(username: params[:username])
    if @user.id != current_user.id
      redirect_to project_path(params[:username], params[:codename])
      return
    end
    @project = Project.find_by(user_id: @user.id, codename: params[:codename])
  end

  def update
    @user = User.find_by(username: params[:username])
    @project = Project.find_by(user_id: @user.id, codename: params[:id])
    
    if @user.id != current_user.id
      redirect_to projects_path(@user.username)
      return
    end

    if @project.nil?
      redirect_to projects_path(@user.username)
      return
    end

    if @project.update(project_params)
      @project.icon.attach(params[:project][:icon]) if params[:project][:icon]
      redirect_to project_path(@project.user.username, @project.codename)
    else
      render :edit
    end
  end

  def destroy
    if params[:username] != current_user.username
      redirect_to project_path(params[:username], params[:codename])
      return
    end

    @user = User.find_by(username: params[:username])
    @project = Project.find_by(user_id: @user.id, codename: params[:codename])
    @project.destroy
    redirect_to projects_path
  end

  private def project_params
    params.require(:project).permit(:title, :codename, :link, :body, :icon, :rss)
  end

  private def page_limit
    20
  end
end

app/views/projects/_form.html.erb
<%= form_with(
  model: project,
  url: path,
  method: method,
  multipart: true,
  data: {
    action: "turbo:submit-end->markdown#clear",
    turbo_frame: :posts,
    turbo: false,
    controller: "turbo-form markdown",
    post_editor_confirm_message: I18n.t("page.confirm_leave"),
    markdown_min_height_value: "100px",
    markdown_placeholder_value: I18n.t("posts.placeholder"),
    markdown_image_uploading_text_value: I18n.t("images.uploading"),
    markdown_image_upload_failed_text_value: I18n.t("images.upload_failed")
  },
) do |f| %>
  <%= render partial: "shared/error_messages", locals: { errors: project.errors.full_messages } %>
  <%= render partial: "shared/notice_messages", locals: { notice: notice } %>
  <div data-controller="file-field">
    <%= image_tag project.icon_url, alt: "", width: "100px", height: "100px", class: "w-20 h-20 object-cover rounded preview" %>
    <button type="button" class="<%= block_link_class %> my-4 text-sm" data-action="file-field#click" >
      <%= I18n.t("form.button.change_file") %>
    </button>
    <%= f.file_field :icon, data: { file_field_target: "field" }, accept: "image/png, image/jpeg", class: "hidden" %>
  </div>
  <%= f.label :title, class: label_class %>
  <%= f.text_field :title, class: text_field_class + " mb-5", placeholder: I18n.t("projects.placeholder.title") %>
  <div class="flex items-center">
    <%= f.label :codename, class: label_class %>
    <span class="ml-2 mb-2 text-xs text-gray-500"><%= I18n.t("projects.notice.codename") %></span>
  </div>
  <%= f.text_field :codename, class: text_field_class + " mb-5", placeholder: I18n.t("projects.placeholder.codename") %>
  <%= f.label :link, class: label_class %>
  <%= f.text_field :link, class: text_field_class + " mb-5", placeholder: "https://" %>
  <%= f.label :body, class: label_class %>
  <div class="<%= text_field_class %> hover:bg-white bg-white mb-5">
    <div>
      <div data-markdown-target="editorContainer">
        <%= f.text_area(
          :body,
          data: { markdown_target: "editor" },
          class: "w-full resize-none min-h-[94px]"
        ) %>
      </div>
      <div class="markdown-body hidden min-h-[100px]" data-markdown-target="preview"></div>
    </div>
    <div class="flex items-center">
      <div class="grow"></div>
      <div class="px-1">
        <button type="button" class="<%= icon_button_class %> transition-all" data-action="markdown#preview" data-markdown-target="previewButton" >
          <div class="i-lucide-eye"></div>
        </button>
        <button type="button" class="<%= icon_button_class %> transition-all hidden" data-action="markdown#edit" data-markdown-target="editorButton" >
          <div class="i-lucide-pen"></div>
        </button>
      </div>
    </div>
  </div>
  <%= f.label :rss, class: label_class %>
  <div class="flex items-center mb-5">
    <label class="">
      <span class="mr-2"><%= I18n.t("projects.notice.rss") %></span>
      <%= f.check_box :rss, class: "" %>
    </label>
  </div>
  <div class="flex">
    <%= f.submit submit_label, class: primary_button_class %>
  </div>
<% end %>

app/views/projects/_item.html.erb
<a class="flex space-x-4 <%= card_class %> border-b dark:hover:border-gray-700" href="<%= project_path(project.user.username, project.codename) %>" data-turbo-frame="_top" >
  <%= image_tag project.icon_url, class: "w-12 h-12 rounded" %>
  <div>
      <h4 class="font-bold"><%= project.title %></h4>
    <div class="flex items-center space-x-2">
      <h5 class="text-sm">#<%= project.codename %></h5>
      <p class="text-sm"><%= project.posts.count > 0 ? "#{project.posts.count} Posts" : "No Post" %></p>
    </div>
  </div>
</a>

app/views/projects/edit.html.erb
<% set_meta_tags(
  title: @project.title,
  og: {
    title: @project.title,
  }
) %>

<%= turbo_frame_tag "timeline" do %>
<div class="mx-auto max-w-3xl w-full p-0 sm:p-4">
  <div class="bg-white dark:bg-dark-card p-4">
    <%= render partial: 'projects/form', locals: { project: @project, path: update_project_path(current_user.username, @project.codename), submit_label: I18n.t("form.submit.update"), method: :patch } %>
    <div class="flex">
      <div class="grow"></div>
      <%= button_to I18n.t("form.submit.delete"), project_path(current_user.username, @project.codename), data: { turbo: false }, onClick: "return confirm('#{I18n.t("projects.confirm_delete")}')", method: :delete, class: "text-red-500 mt-10 text-sm" %>
    </div>
  </div>
</div>
<% end %>

app/views/projects/index.html.erb
<% set_meta_tags(
  title: I18n.t("pages.projects", user: @user.name),
  og: {
    title: I18n.t("pages.projects", user: @user.name),
  }
) %>

<%= turbo_frame_tag "timeline" do %>
<div class="w-full mx-auto max-w-3xl p-4">
  <div id="profile-<%= @user.id %>" data-turbo-permanent>
    <%= render partial: "users/profile", locals: { user: @user } %>
  </div>
  <div id="user-nav-container" class="z-[50]" data-turbo-permanent>
    <div class="<%= nav_class %>">
      <div class="<%= nav_list_class %>">
        <%= render partial: "users/user_nav", locals: { user: @user } %>
      </div>
    </div>
  </div>
  <div class="max-w-3xl mx-auto">
    <%= turbo_frame_tag "project_list", src: projects_list_path(@user.username), loading: :lazy %>
  </div>
</div>
<% end %>

app/views/projects/index.turbo_stream.erb
<%= turbo_stream.append "projects" do %>
  <%= render partial: 'projects/item', collection: @projects, as: :project %>
<% end %>

<% if @next_page.present? && !params[:limit].present? %>
  <%= turbo_stream.replace "projects_load_more" do %>
    <%= turbo_frame_tag "projects_load_more", src: projects_path(@user.username, page: @next_page, format: :turbo_stream), loading: :lazy %>
  <% end %>
<% else %>
  <%= turbo_stream.replace "projects_loading" do %>
  <% end %>
  <%= turbo_stream.replace "projects_load_more" do %>
  <% end %>
<% end %>

app/views/projects/list.html.erb
<%= turbo_frame_tag "project_list" do %>
  <div>
    <% if current_user == @user %>
      <a class="flex items-center space-x-2 <%= card_class %> border-b dark:hover:border-gray-700" href="<%= new_project_path %>" data-turbo-frame="_top">
        <div class="i-lucide-plus-circle text-xl"></div>
        <div class="font-bold"><%= I18n.t("projects.start") %></div>
      </a>
    <% end %>
    <div data-testid="project-list">
      <%= render partial: 'projects/item', collection: @projects, as: :project %>
    </div>
  </div>
<% end %>

app/views/projects/new.html.erb
<% set_meta_tags(
  title: "New Project",
  og: {
    title: "New Project",
  }
) %>

<%= turbo_frame_tag :timeline do %>
<div class="max-w-3xl mx-auto w-full mt-4 px-4">
  <div class="bg-white dark:bg-dark-card p-4">
    <%= render partial: 'projects/form', locals: { project: @project, path: create_project_path, submit_label: I18n.t("form.submit.create"), method: :post } %>
  </div>
</div>
<% end %>

app/views/projects/show.html.erb
<% set_meta_tags(
  title: @project.title,
  og: {
    title: @project.title,
  }
) %>

<%= turbo_frame_tag "timeline" do %>
<div class="w-full p-4 max-w-3xl mx-auto">
  <div class="mb-4 w-full">
    <div class="flex p-4 space-x-4 w-full mb-4 bg-white dark:bg-dark-card mt-4 px-4">
      <%= image_tag @project.icon_url, class: "w-20 h-20 rounded" %>
      <div class="grow">
        <div class="flex w-full items-start mb-1">
          <h1 class="grow font-bold text-xl"><%= @project.title %></h1>
          <% if @project.user == current_user %>
            <div class="ml-2 w-24">
              <%= link_to edit_project_path(current_user.username, @project.codename), class: "#{block_link_class} text-sm inline-flex", data: { turbo_frame: "_top" }  do %>
                <div class="i-lucide-pen mr-1"></div>
                <%= I18n.t("form.submit.edit") %>
              <% end %>
            </div>
          <% end %>
        </div>
        <a href="<%= user_path(@project.user.username) %>" class="mb-1  items-center text-sm flex space-x-2 hover:underline" data-turbo-frame="_top">
          <p><%= @project.user.name %></p>
          <p class="text-gray-500">@<%= @project.user.username %></p>
        </a>
        <% if @project.link.present? %>
          <%= link_to @project.link, class: "text-blue-400 items-center text-sm inline-flex hover:underline", target: "_blank" do %>
            <span class="i-lucide-link block mr-1"></span>
            <%= @project.link.sub("https://", "").sub("http://", "").truncate(32) %>
          <% end %>
        <% end %>
        <% if @project.rss %>
          <div class="text-sm flex items-center">
            <div class="i-ri-rss-fill mr-1"></div>
            <a href="<%= feed_path(@project.user.username) %>" class="hover:underline" target="_top">
              <%= I18n.t("projects.rss") %>
            </a>
          </div>
        <% end %>
      </div>
    </div>
    <div class="text-left w-full <%= card_class %> py-8">
      <div class="markdown-body" data-controller="image-modal">
        <%= @project.html.html_safe %>
      </div>
    </div>
  </div>
  <div>
    <% if @posts.empty? %>
    <p class="w-full text-center py-20 font-bold"><%= I18n.t("posts.not_found") %></p>
    <% else %>
    <div class="hidden sm:block">
        <%= turbo_stream_from "posts" %>
      </div>
      <%= turbo_frame_tag "posts", target: "_top" do %>
      <% end %>

      <div class="h-1">
        <%= turbo_frame_tag "load_more", src: project_path(@user.username, @project.codename, format: :turbo_stream), loading: :lazy  %>
        <%= turbo_frame_tag "loading" do %>
          <%= render partial: "shared/loading" %>
          
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/projects/show.turbo_stream.erb
<%= turbo_stream.append "posts" do %>
  <%= render partial: 'posts/post', collection: @posts, locals: { on_timeline: true }  %>
<% end %>

<% if @next_page.present? %>
  <%= turbo_stream.replace "load_more" do %>
    <%= turbo_frame_tag "load_more", src: project_path(@user.username, @project.codename, page: @next_page, format: :turbo_stream), loading: :lazy %>
  <% end %>
<% else %>
  <%= turbo_stream.replace "loading" do %>
  <% end %>
<% end %>