config/routes.rb
Rails.application.routes.draw do
  passwordless_for :users, at: '/'

  get 'notifications/index'

  get "t/sitemap", to: "sitemap#index", as: :sitemap, defaults: { format: "xml" }

  get 'sign_up', to: 'users#new', as: :sign_up
  post 'users/confirm', to: 'users#confirm', as: :confirm
  get 'users/register/:token', to: 'users#register', as: :register
  post 'users', to: 'users#create', as: :create_user
  delete 'users/:id', to: 'users#destroy', as: :delete_user

  get '/notifications', to: 'notifications#index', as: :notifications

  root 'posts#index'
  get "/latest", to: "posts#latest", as: :latest
  get "/pinned", to: "posts#pinned", as: :pinned
  get "posts/:id", to: "posts#show", as: :post
  post "posts", to: "posts#create", as: :create_post
  patch "posts/:id", to: "posts#update", as: :update_post
  delete "posts/:id", to: "posts#destroy", as: :delete_post
  get '/posts/:id/pin_button', to: 'posts#pin_button', as: :post_pin_button

  post '/posts/:post_id/pins', to: 'pins#create', as: :create_pin
  delete '/posts/:post_id/pins/:id', to: 'pins#destroy', as: :delete_pin

  get '/posts/:post_id/reactions', to: 'post_reactions#index', as: :post_reactions
  post '/posts/:post_id/reactions', to: 'post_reactions#create', as: :create_post_reaction
  delete '/posts/:post_id/reactions/:id', to: 'post_reactions#destroy', as: :delete_post_reaction

  get '/posts/:post_id/comments', to: 'comments#index', as: :comments
  post '/posts/:post_id/comments', to: 'comments#create', as: :create_comment
  delete '/posts/:post_id/comments/:id', to: 'comments#destroy', as: :delete_comment
  patch '/posts/:post_id/comments/:id', to: 'comments#update', as: :update_comment

  post '/posts/:post_id/comments/:comment_id/reactions', to: 'comment_reactions#create', as: :create_comment_reaction
  delete '/posts/:post_id/comments/:comment_id/reactions/:id', to: 'comment_reactions#destroy', as: :delete_comment_reaction
  
  get 'settings', to: 'settings#edit', as: :settings
  get 'settings/export', to: 'settings#export', as: :export_settings
  get 'settings/exports/:id/download', to: 'settings#download_export', as: :download_export
  patch 'settings/profile', to: 'settings#update_profile', as: :update_profile
  patch 'settings/theme', to: 'settings#update_theme', as: :update_theme
  patch 'settings/access_token', to: 'settings#update_access_token', as: :update_access_token

  get 'privacy/(:locale)', to: 'pages#privacy', as: :privacy
  get 'terms/(:locale)', to: 'pages#terms', as: :terms
  get 'about/(:locale)', to: 'pages#about', as: :about
  get 'docs/(:locale)', to: 'pages#docs', as: :docs

  get '/:username', to: 'users#actor', as: :actor, constraints: lambda { |request| request.format == :json }
  get '/:username', to: 'users#show', as: :user, constraints: lambda { |request| request.format != :json }
  get '/:username/feed', to: 'users#feed', as: :feed
  get 'users/:username' => redirect('/%{username}')
  get '/:username/projects', to: 'projects#index', as: :projects
  get '/:username/projects/list', to: 'projects#list', as: :projects_list
  get '/:username/projects/:codename', to: 'projects#show', as: :project
  get 'projects/new', to: 'projects#new', as: :new_project
  post 'projects', to: 'projects#create', as: :create_project
  get '/:username/projects/:codename/edit', to: 'projects#edit', as: :edit_project
  patch '/:username/projects/:id', to: 'projects#update', as: :update_project
  delete '/:username/projects/:codename', to: 'projects#destroy', as: :delete_project
  post '/:username/follows', to: 'follows#create', as: :follow_user
  delete '/:username/follows', to: 'follows#destroy', as: :unfollow_user
  get '/:username/followers', to: 'users#followers', as: :followers
  get '/:username/following', to: 'users#following', as: :following

  namespace :api do
    namespace :v1 do
      get 'posts', to: 'posts#index', as: :posts
      get 'posts/following', to: 'posts#following', as: :posts_following
      get 'posts/pinned', to: 'posts#pinned', as: :posts_pinned
      get 'posts/:id', to: 'posts#show', as: :post
      post 'posts', to: 'posts#create', as: :create_post
      patch 'posts/:id', to: 'posts#update', as: :update_post
      delete 'posts/:id', to: 'posts#destroy', as: :delete_post
      post 'comments/previews', to: 'comments#preview', as: :preview_comment
      post 'posts/:post_id/comments', to: 'comments#create', as: :create_comment
      patch 'posts/:post_id/comments/:id', to: 'comments#update', as: :update_comment
      delete 'posts/:post_id/comments/:id', to: 'comments#destroy', as: :delete_comment
      post 'projects/previews', to: 'projects#preview', as: :preview_project
      post 'projects', to: 'projects#create', as: :create_project
      patch 'projects/:id', to: 'projects#update', as: :update_project
      delete 'projects/:id', to: 'projects#destroy', as: :delete_project
      post 'posts/preview', to: 'posts#preview', as: :preview_post
      get 'blobs/:id/url', to: 'blobs#url', as: :blob_url
      post 'notifications/read', to: 'notifications#read', as: :read_notifications
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  include Markdownable

  belongs_to :user
  has_and_belongs_to_many :projects
  has_many :comments, dependent: :destroy
  has_many :post_reactions, dependent: :destroy
  has_many_attached :images
  has_many :pins, dependent: :destroy
  has_many :cheers, dependent: :destroy

  after_save -> { projects.each(&:touch) }

  scope :latest, -> { order(updated_at: :desc) }
  scope :following, -> (user) {where(user: user.followee_users).or(where(user: user)) }
  scope :pinned_by, -> (user) { joins(:pins).where(pins: {user: user}) }
  scope :trending, -> {
    joins(:post_reactions)
    .select('posts.*, count(post_reactions) as reaction_count')
    .group('posts.id')
    .order('reaction_count desc')
    .where('posts.created_at > ?', 1.week.ago)
  }

  def self.score_per_day(user)
    posts = Post
      .where(user: user)
      .group("created_at::DATE")
      .count
    comments = Comment
      .where(user: user)
      .group("created_at::DATE")
      .count
    count = posts.merge(comments)
    score = {}
    count.each do |date, c|
      if c == 0
        score[date] = 0
      elsif c > 0 && c <= 5
        score[date] = 1
      elsif c > 5 && c <= 10
        score[date] = 2
      elsif c > 10 && c <= 20
        score[date] = 3
      elsif c > 20 && c <= 30
        score[date] = 4
      elsif c > 30
        score[date] = 5
      end
    end
    score
  end

  def attach_projects!
    projects.clear

    body.scan(/#(\w+)/).flatten.each do |codename|
      project = user.projects.find_by(codename: codename)
      if project.present? && !projects.include?(project)
        projects << project
      end
    end

    save
  end

  def pinned_by?(user)
    pins.where(user: user).exists?
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class PostsController < ApplicationController
      before_action :authenticate_user!, only: [:create, :update, :destroy]
      skip_forgery_protection

      def index
        current_page = params[:page] ? params[:page].to_i : 0
        per_page = params[:per_page] ? params[:per_page].to_i : 10
        posts = Post.offset(per_page*current_page)
          .latest
          .limit(per_page)
        render json: { posts: PostSerializer.render_as_hash(posts) }
      end

      def following
        unless current_user
          render json: { error: "Unauthorized" }, status: 401
          return
        end

        current_page = params[:page].to_i
        per_page = params[:per_page].to_i
        posts = Post.offset(per_page*current_page)
          .latest
          .limit(per_page)
          .following(current_user)
        render json: { posts: PostSerializer.render_as_hash(posts) }
      end

      def trending
        render json: { posts: PostSerializer.render_as_hash(Post.trending.limit(5))}
      end

      def pinned
        unless current_user
          render json: { error: "Unauthorized" }, status: 401
          return
        end

        current_page = params[:page].to_i
        per_page = params[:per_page].to_i
        posts = Post.offset(per_page*current_page)
          .pinned_by(current_user)
          .latest
          .limit(per_page)
        
        render json: { posts: "hoge" }
      end

      def show
        post = Post.includes(comments: :user).find_by(id: params[:id])
        if post.nil?
          render json: { error: "Not found" }, status: 404
          return
        end
    
        comments = post.comments
          .includes(:user, comment_reactions: :user)
          .latest
        
        render json: { post: PostSerializer.render_as_hash(post, view: :thread) }
      end    

      def preview
        post = Post.new(body: post_params[:body])
        render json: { body: post.html.html_safe }
      end

      def create
        post = Post.new(post_params)
        post.user = current_user
        post.attach_projects!
        post.save
        CreateProjectJob.perform_later(post)
        render json: { post: PostSerializer.render_as_hash(post) }
      end

      def update
        post = Post.find(params[:id])
        if post.user != current_user
          render json: { error: "You are not authorized to edit this post." }, status: 401
          return
        end
        post.update(post_params)
        post.attach_projects!
        CreateProjectJob.perform_later(post)
        render json: { post: PostSerializer.render_as_hash(post) }
      end

      def destroy
        post = Post.find(params[:id])
        if post.user != current_user
          render json: { error: "You are not authorized to delete this post." }, status: 401
          return
        end
        post.destroy
        render json: {}, status: 204
      end

      private def post_params
        params.require(:post).permit(:body)
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def trending
    if request.format == "text/html"
      set_cache_control_headers
    end
    @posts = Rails.cache.fetch("posts/trending", expires_in: 3.hours) do
      Post.trending
        .limit(5)
    end
  end

  def menu
    @post = Post.find(params[:id])
  end

  def pin_button
    @post = Post.find(params[:id])
  end

  def main
    @post = Post.find(params[:id])
    @post_reaction = PostReaction.new
  end

  def form
    @post = Post.new
  end

  def editor
    @post = Post.find(params[:id])
  end

  def index
    if request.format == "text/html"
      set_cache_control_headers
    end
    @post = Post.new
    @post_reaction = PostReaction.new
    @current_page = params[:page].to_i

    if current_user
      @posts = Post.offset(page_limit*@current_page)
        .latest
        .limit(page_limit)
        .following(current_user)
      @next_page = @current_page + 1 if Post.following(current_user).count > page_limit*@current_page + page_limit
    else
      @posts = Rails.cache.fetch("posts/latest/pages/#{@current_page}/per/#{page_limit}", expires_in: 10.minutes) do
        Post.offset(page_limit*@current_page)
          .latest
          .limit(page_limit)
      end
      @next_page = @current_page + 1 if Post.all.count > page_limit*@current_page + page_limit
    end
  end

  def latest
    if request.format == "text/html"
      set_cache_control_headers
    end
    @post = Post.new
    @post_reaction = PostReaction.new
    @current_page = params[:page].to_i

    @posts = Rails.cache.fetch("posts/latest/pages/#{@current_page}/per/#{page_limit}", expires_in: 10.minutes) do
      Post.offset(page_limit*@current_page)
        .latest
        .limit(page_limit)
    end
    @next_page = @current_page + 1 if Post.all.count > page_limit*@current_page + page_limit
  end

  def pinned
    if request.format == "text/html"
      set_cache_control_headers
    end
    @post = Post.new
    @post_reaction = PostReaction.new
    @current_page = params[:page].to_i

    all = Post.offset(page_limit*@current_page)
      .pinned_by(current_user)
      .latest
    @posts = all.limit(params[:limit] || page_limit)
    @next_page = @current_page + 1 if all.count > page_limit*@current_page + page_limit
  end

  def show
    if request.format == "text/html"
      set_cache_control_headers
    end
    @post = Post.includes(comments: :user).find_by(id: params[:id])
    @post_reaction = PostReaction.new
    @comment_reaction = CommentReaction.new
    if @post.nil?
      render file: "#{Rails.root}/public/404.html", status: :not_found
      return
    end
    @current_page = params[:page].to_i

    @comments = @post.comments.offset(page_limit*@current_page)
      .includes(:user, comment_reactions: :user)
      .latest
      .limit(page_limit)
    @next_page = @current_page + 1 if Post.all.count > page_limit*@current_page + page_limit
    @comment = Comment.new
  end

  def pin_button
    @post = Post.find(params[:id])
  end

  def editor
    @post = Post.find(params[:id])
  end

  def form
    @post = Post.new
  end

  def create
    @post = Post.create(post_params.merge(user: current_user))
    @post.attach_projects!
    CreateProjectJob.perform_later(@post)
  end

  def update
    @post = Post.find(params[:id])

    if @post.user != current_user
      render json: { error: 'You are not authorized to edit this post.' }, status: :unauthorized
      return
    end

    @post.update(post_params)
    @post.attach_projects!

    CreateProjectJob.perform_later(@post)
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.user != current_user
      render json: { error: 'You are not authorized to delete this post.' }, status: :unauthorized
      return
    end

    @post.destroy!
    redirect_to root_path, status: 303
  end

  private def post_params
    params.require(:post).permit(:body, images: [])
  end

  private def page_limit
    10
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def ogp_image(post)
    "https://res.cloudinary.com/dw1xpb7if/image/upload/c_fit,g_west,h_190,l_text:jxfzypcvmrsidywwbv9l.ttf_48:#{post.user.name},w_448,x_270,y_-200/c_fit,h_128,l_fetch:#{Base64.encode64(post.user.avatar_icon).gsub(/\n/, "")},r_100,w_128,x_-420,y_-180/c_fit,g_west,l_text:jxfzypcvmrsidywwbv9l.ttf_32:@#{post.user.username},w_339,x_270,y_-145/c_fit,g_north_west,l_text:jxfzypcvmrsidywwbv9l.ttf_60:#{post.truncated(48).gsub(/#/, CGI.escape("#"))},w_1000,x_120,y_240/v1691627490/v1693713928/ob6029tvw9p1auvry2hd.png"
  end
end

app/views/posts/_item.html.erb
<div id="<%= item.id %>" class="<%= card_class %>  transition-opacity animate-fade-in <%= strip_tags(item.html).length < 64 && !item.comments.present? ? "max-w-sm mx-auto" : "" %>">
  <div class="mb-3 flex items-center space-x-1">
    <div class="flex hover:underline items-center space-x-1 relative">
      <%= render partial: 'shared/avatar', locals: { user: item.user } %>
    </div>
    <time class="text-gray-400 text-sm"><%= time_ago_in_words(item.created_at) %></time>
    <div class="grow"></div>
  </div>
  <div class="markdown-body" style="<%= item.emoji_only? ? "font-size: 32px;" : "" %>">
    <%= item.html(400).html_safe %>
  </div>
  <div class="flex items-end">
    <div class="flex mt-3 items-center w-full flex-wrap overflow-hidden">
      <%= render partial: 'shared/post_reactions', locals: { current_user: current_user, post: item, reaction: @post_reaction } %>
      <div class="flex items-center flex-wrap">
      <% item.comments.order(created_at: :desc).limit(2).each do |comment| %>
        <div class="rounded-full bg-gray-50 dark:bg-slate-700 dark:hover:bg-slate-600  flex items-center py-[4px] px-2 mr-1 text-sm my-1">
          <%= image_tag comment.user.avatar_icon, alt: comment.user.username,width:"20px", height: "20px", class: "mr-1 w-5 h-5 rounded-full block" %>
          <%= strip_tags(comment.html).truncate(20) %>
        </div>
      <% end %>
      </div>
      <% if item.comments.length > 0 %>
        <%= link_to post_path(id: item.id), class: "cursor-pointer items-center flex rounded-full p-relative px-2 py-[4px] my-1 hover:bg-gray-100 bg-gray-50 dark:bg-slate-700 dark:hover:bg-slate-600 transition-all", data: { turbo: false } do %>
          <p class="text-gray-600 dark:text-slate-50  text-sm flex items-center space-x-1">
            <%= image_tag "icons/comment.svg", alt: "comment", width:"14px", height: "14px", class: "icon" %>
            <span class="text-xs"><%= item.comments.count %></span>
          </p>
        <% end %>
      <% end %>
      <div class="grow"></div>
    </div>
    <%= link_to post_path(id: item.id), class: icon_button_class do %>
      <%= image_tag "icons/forward.svg", alt: "forward", class: "icon w-5 h-5" %>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="<%= "#{card_class} overflow-visible flex border dark:border-dark-border rounded mb-4 shadow-sm transition-all animate-fade-in w-full post-card" %>" data-controller="post-show" data-testid="<%= post.body %>" >
  <div class="w-[42px]">
    <%= link_to user_path(username: post.user.username), class: " text-sm block flex items-center hover:underline flex-wrap", data: { turbo_frame: "_top" } do %>
      <%= image_tag post.user.avatar_icon, alt: "", width: "20px", height: "20px", class: "w-8 h-8 rounded-full mr-2 block" %>
    <% end %>
  </div>
  <div class="w-[calc(100%-42px)] overflow-visible z-[100]">
    <div class="mb-4 z-[100]">
      <div class="flex flex-row mb-3 items-center space-x-1 z-[100]">
        <div class="flex w-[calc(100%-42px)] items-center space-x-1 whitespace-nowrap overflow-hidden overflow-ellipsis">
          <%= link_to user_path(username: post.user.username), class: " text-sm block flex gap-1 items-center hover:underline", data: { turbo_frame: "_top" } do %>
            <span class="font-bold"><%= post.user.name %></span>
            <span class="text-gray-400"><%= post.user.username_with_at %></span>
          <% end %>
          <time class="text-gray-400 text-sm" title="<%= post.created_at %>"><%= time_ago_in_words(post.created_at) %></time>
        </div>
        <div class="flex items-center w-[42px] space-x-1 overflow-visible z-[100]">
          <div class="grow"></div>
          <div data-controller="menu" data-post-show-target="menu" class=" overflow-visible relative">
            <button class="<%= icon_button_class %>" data-action="menu#open" >
              <div class="i-lucide-more-horizontal"></div>
            </button>
            <div data-action="click->menu#close" data-menu-target="backdrop" class="<%= backdrop_class %>"></div>
            <div class="overflow-scroll absolute top-0 right-[48px] z-[100] hidden w-48 bg-white dark:bg-dark-card shadow-sm rounded border dark:border-dark-border scrollbar-none transition-all animate-down p-2" data-menu-target="dropdown">
              <button class="<%= block_link_class %> w-full"  data-controller="copy" data-copy-copied-text-value="<%= I18n.t("clipboard.copied") %>" data-copy-content-value="<%= post.body %>" data-action="menu#close">
                <div class="i-lucide-copy"></div>
                <%= I18n.t("posts.copy-markdown") %>
              </button>
              <button class="<%= block_link_class %> w-full"  data-controller="copy" data-copy-copied-text-value="<%= I18n.t("clipboard.copied") %>" data-copy-content-value="<%= post_url(post) %>" data-action="menu#close">
                <div class="i-lucide-link"></div>
                <%= I18n.t("posts.copy-link") %>
              </button>
              <% if current_user %>
                <%= turbo_frame_tag :pin_button do %>
                  <%= render partial: "shared/pin_button", locals: { post: post } %>
                <% end %>
              <% end %>
              <% if current_user == post.user %>
                <button class="<%= block_link_class %> w-full" data-action="post-show#edit menu#close" data-post-show-target="editButton" >
                  <div class="i-lucide-pen"></div>
                  <%= I18n.t("posts.edit") %>
                </button>
                <div class="mt-[1px]">
                  <%= button_to(
                    delete_post_url(id: post.id),
                    method: :delete,
                    class: "#{block_link_class}  w-full text-red-400 dark:text-red-400",
                    onClick: "return confirm('#{I18n.t('posts.confirm_delete')}')",
                    data: { turbo: false, post_show_target: "deleteButton", action: "menu#close" },
                  ) do %>
                    <div class="i-lucide-trash"></div>
                    <%= I18n.t("posts.delete") %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
          <button class="hidden <%= icon_button_class %>" data-action="post-show#close" data-post-show-target="closeButton">
            <div class="i-lucide-x"></div>
          </button>
        </div>
      </div>
      <div data-post-show-target="show" data-controller="image-modal twitter" class="markdown-body">
        <%= turbo_frame_tag :post do %>
          <%= post.html.html_safe %>
        <% end %>
      </div>
    <%= turbo_frame_tag "post_editor-#{post.id}" do %>
      <% if current_user == post.user %>
      <div class="hidden" data-post-show-target="editor">
        <%= form_with(
          model: post,
          url: update_post_path(id: post.id),
          id: "post-form",
          data: {
            action: "turbo:submit-end->post-show#close",
            turbo_frame: :post,
            controller: "turbo-form markdown",
            post_editor_confirm_message: I18n.t("page.confirm_leave"),
            markdown_min_height_value: "100px",
            markdown_model_value: "post",
            markdown_placeholder_value: I18n.t("posts.placeholder"),
            markdown_image_uploading_text_value: I18n.t("images.uploading"),
            markdown_image_upload_failed_text_value: I18n.t("images.upload_failed")
          },
          class: "grow transition-all"
        ) do |f| %>
          <div>
            <%= flash[:error] %>
            <div class="max-w-3xl mx-auto">
              <div class="">
                <div data-markdown-target="editorContainer">
                  <%= f.text_area :body, data: { markdown_target: "editor", post_editor_target: "body" }, class: "prose resize-none min-h-[114px]" %>
                </div>
                <div class="markdown-body hidden min-h-[120px]" data-markdown-target="preview"></div>
              </div>
            </div>
          </div>
          <div class="flex pt-3 w-full items-center bg-none">
            <div class="grow"></div>
            <div class="px-1">
              <button
                type="button"
                class="<%= icon_button_class %>"
                data-controller="tooltip"
                data-tooltip-text-value="<%= I18n.t('posts.image') %>"
                data-action="markdown#attachImage"
                data-testid="attach-image"
              >
                <div class="i-lucide-image"></div>
              </button>
            </div>
            <div class="px-1">
              <button type="button" class="<%= icon_button_class %>" data-action="markdown#preview" data-markdown-target="previewButton" >
                <div class="i-lucide-eye"></div>
              </button>
              <button type="button" class="<%= icon_button_class %> hidden" data-action="markdown#edit" data-markdown-target="editorButton" >
                <div class="i-lucide-pen"></div>
              </button>
            </div>
            <div class="ml-2">
              <%= f.submit I18n.t('posts.update'), disabled: true, class: primary_button_class, data: { post_editor_target: "publish" } %>
            </div>
          </div>
        <% end %>
      </div>
      <% end %>
    <% end %>

    </div>
    <% if post.comments.count > 0 %>
      <div class="text-xs flex items-center">
        <%= image_tag post.comments.latest&.first&.user.avatar_icon, class: "w-4 h-4 rounded-full mr-1" %>
        <p class="opacity-70"><%= post.comments.latest&.first&.truncated(32) %></p>
        <% if post.comments.count > 1 %>
          <div class="text-xs opacity-70 ml-2">
            <%= post.comments.count - 1  %> more
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="flex items-end">
      <div class="flex grow items-center flex-wrap w-[calc(100%-34px)]">
        <%= turbo_frame_tag :post_reactions do %>
          <%= render partial: 'post_reactions/list', locals: { post: post } %>
        <% end %>
      </div>
      <% if on_timeline %>
        <%= link_to post_path(post.id), class: icon_button_class, data: { turbo: false } do %>
          <div class="i-lucide-arrow-right"></div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.replace "form" do %>
  <%= render partial: "posts/form", locals: { post: @post } %>
<% end %>

<%= turbo_stream.prepend "posts" do %>
 <%= render partial: "posts/post", locals: { post: @post, on_timeline: true } %>
<% end %>

app/views/posts/destroy.turbo_stream.erb
<%= turbo_stream.remove @post %>

app/views/posts/index.html.erb
<div class="flex grow relative ">
  <div class="grow w-full max-w-3xl mx-auto p-4" id="main">
    <%= turbo_frame_tag "timeline" do %>
    <div class="max-w-3xl mx-auto">
      <% if current_user %>
        <div class="flex w-full <%= card_class %> space-x-3 border rounded mb-4 shadow-sm dark:border-dark-border">
          <div class="transition-all w-[32px]">
            <%= link_to user_path(username: current_user.username), class: "w-8 flex items-center space-x-1 hover:underline mt-1" do %>
              <%= image_tag current_user.avatar_icon, alt: "", class: "w-8 h-8 object-cover rounded-full" %>
            <% end %>
          </div>
          <div class="w-[calc(100%-45px)]">
            <%= render partial: "posts/form", locals: { post: @post, page: @page } %>
          </div>
        </div>
      <% end %>
      <%= turbo_frame_tag "posts", target: "_top" do %>
      <% end %>

      <%= turbo_frame_tag "first_loading" do %>
        <div class="fixed top-1/2 left-1/2 -translate-x-1/2 text-4xl text-gray-500 -translate-y-1/2">
          <div class="i-svg-spinners-bars-rotate-fade"></div>
        </div>
      <% end %>
      <%= turbo_frame_tag "loading" do %>
      <% end %>
      <%= turbo_frame_tag "load_more", src: root_path(format: :turbo_stream)  %>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/latest.html.erb
<div class="flex grow relative ">
  <div class="grow w-full p-4 max-w-3xl mx-auto" id="main">
    <%= turbo_frame_tag "timeline" do %>
    <div class="max-w-3xl mx-auto">
      <%= turbo_frame_tag "posts", target: "_top" do %>
      <% end %>

      <%= turbo_frame_tag "first_loading" do %>
        <div class="fixed top-1/2 left-1/2 -translate-x-1/2 text-4xl text-gray-500 -translate-y-1/2">
          <div class="i-svg-spinners-bars-rotate-fade"></div>
        </div>
      <% end %>
      <%= turbo_frame_tag "loading" do %>
      <% end %>
      <%= turbo_frame_tag "load_more", src: latest_path(format: :turbo_stream)  %>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/latest.turbo_stream.erb
<%= turbo_stream.replace "first_loading" do %>
<% end %>

<%= turbo_stream.append "posts" do %>
  <% if @posts.present? %>
    <%= render partial: "posts/post", collection: @posts, locals: { additional_class: "border-b", on_timeline: true } %>
  <% else %>
    <div class="<%= card_class %> font-bold text-center">
      <div class="card-body">
        <p class="card-text">
          <%= I18n.t("following.empty") %>
      </div>
    </div>
  <% end %>
<% end %>

<%= turbo_stream.replace "loading" do %>
  <div class="flex w-full py-8 text-4xl text-gray-500">
    <div class="grow"></div>
    <div class="i-svg-spinners-bars-rotate-fade"></div>
    <div class="grow"></div>
  </div>
<% end %>

<%= turbo_stream.replace "load_more" do %>
  <div class="h-1">
    <%= turbo_frame_tag "load_more", src: latest_path(page: @next_page, format: :turbo_stream), loading: :lazy %>
  </div>
<% end %>

app/views/posts/update.turbo_stream.erb
<%= turbo_stream.replace :post do %>
  <%= @post.html.html_safe %>
<% end %>